### ISSUE TITLE
Add more presets

### ISSUE THREAD

**Issue by miguelTorrinhaPereira** [uniwix/casioplot#34]
the following preset config files could be useful:
- 1080p
- 720p
- 540p
- 360p
- 240p
- 1440p?
They would be easy to implement:
```toml
default_to = "presets/default.toml"

[canvas]
width = 1920
height = 1080
```
