### ISSUE TITLE
Window pops up for a second then closes?

### ISSUE THREAD

**Issue by Dulio-exe** [uniwix/casioplot#37]
Hey I'm trying to use this library but it automatically closes immediately. I'm running this on both wsl and windows, however both have the same result. I'm also running this on python 3.12.4.

**Comment by uniwix** [comment]
Hi,
Have you tried to run the examples?
If it was the case, could you please send the script you are trying to run?
Thanks

**Comment by uniwix** [comment]
You may be interested by this https://casioplot.readthedocs.io/en/latest/settings.html
You need to manually set the window to keep open at exit using 
```toml
[showing_screen]
# Keep the window open at exit.
close_window = false
```
