### ISSUE TITLE
toml config rules

### ISSUE THREAD

**Issue by uniwix** [uniwix/casioplot#7]
config.toml:
```toml
preset="90e.toml"

[margins]
left = 8
top = 10

[size]
width = 400
height = 200
```
is interpreted as

```python
casioplot_settings.config_to("90e.toml")
casioplot_settings.set(left_margin=8)
casioplot_settings.set(top_margin=10)
casioplot_settings.set(width=400)
casioplot_settings.set(height=200)
```

**Comment by uniwix** [comment]
### All settings:
```toml
# extend preset
preset="default.toml"

[screen]
# use tkinter to show the screen
show = true
# save the screen in the disk
save = false
filename = "casioplot"
format = "png"

# margins around the screen
[margins]
left = 0
right = 0
top = 0
bottom = 0

# size of the screen
[size]
width = 400
height = 200

# sets a background image
[background]
path = "default.png"

# both size and background may not be used at the same time
```

This is a proposal of settings and their default values

**Comment by uniwix** [comment]
```toml
[screen]
# save 1 image each n call of `show_screen()`
rate = n
```
